### ISSUE TITLE
does the project support Openstack Ocata?

### ISSUE THREAD

**Issue by Daqu** [Crystal-SDS/filter-middleware#1]
hi guys, you mention that the examples tested in openstack kilo. have you tested it in openstack's new version?

**Comment by RaulGracia** [comment]
Hi @Daqu, 

Yes, actually in our infrastructure we have been using Ocata for several weeks and the framework is working fine. In fact, the version of Swift in the provided development VM (2.11) is also newer than Kilo. 

Regards,
Raúl.

**Comment by Daqu** [comment]
oops, good job! I'm tring to deploy crystal without your vm so that I can understand your code.Thanks for your answer!
